<script type="text/javascript">
 	 require(['apexxCse'], function () {});
 	 require(['jsEnc'], function () {});

	require(['jquery', 'jquery/ui'], function($){
  //	jQuery(document).ready( function() {
      window.onload = function() { 
      //	alert("inner-apexx");
       // APEXX.setPublicKey("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0AO1ls0wvY1P08OdfzaaNrPnuCzI5SJqIT3OpfkOuyOCX3s+cv30wVohX4e70CByqR6VIQEmOvNa2VJKJlRnam552MvxwJSXgzoJCbWXqmqMHJEnbepBcxLyHeG/XLeKHy8iKKUEEk3cKbnIq+EZIjeo4rNQscnT9ZgKGfPVXVSKHIjQe7Dhg5hP8A3EweDzSnm0JwqBCD1TqIxW8uXdzH2i4JrbPlv1bP+o2J27tlWLHrfBD7a8OS8yI349w8djroyQR2QotljpIy/jNCVodfrw98voij4e7EbB436LU1wP5kd45iiZqACE9aWQ04TnSDWe4toOXikh72l70BmJTQIDAQAB");
     }
      	//alert("loaded");
  });
//})
</script>